### PR TITLE
Fixes #67 write errors and #68 better open errors 

### LINKED ISSUE #67: Error: write command timed out after 5s.
Sending multiple commands to the device can cause a write to fail. This seems to happen more consistently on Windows but really it could happen at anytime. We need to serialize the send cmd and get response to the device.

### PR DESCRIPTION
**Pull request by minorgal**
#67 was happening because if multiple write commands stacked up on each other the device was not happy about it. Really we need to ensure not only one write happens at a time but that the response has returned before blasting another command down to the device. By just adding the commands to the queue and having and interval write out of that queue we are able to control how we talk to the device. Most of the time the interval fires and does nothing but I am open to input on timeouts or different ways to accomplish what we need.

#68 Sometimes the device fails to get the command and response characteristics. In these cases the open failed but the caller wasn't aware of it. Removing the try/catch allowed the existing code to work as expected. 

Note: there was some additional cleanup in the library I did that shouldn't change functionality but makes the code cleaner and have better messages.

### CODE REVIEW

**Comment by minorgal** [comment]
@jordanaustin I am waiting to merge this PR until you get a chance to review it.

File: src/Device.js [hunk 1]
```diff
@@ -70,21 +70,17 @@ export default class Device extends EventEmitter {
...
-      await this._getDefaultSensorsMask();
-      await this._getAvailableSensors();
-
-      this._onOpened();
-
-      if (autoStart) {
-        this.start();
-      }
-    } catch (err) {
-      console.error(err);
```
Comment (jordanaustin) [inline src/Device.js]: It seems like we should throw a new error here, rather than remove our catch

File: src/Device.js [hunk 2]
```diff
@@ -164,17 +160,33 @@ export default class Device extends EventEmitter {
...
+      // and nothing else is sent until the response or timeout happens.
+      this.deviceWriteInterval = setInterval(() => {
+        if (this.writeQueue && this.writeQueue.length > 0) {
+          const q = this.writeQueue[0];
+          if (!q.written) {
+            this._writeToDevice(q.buffer);
+            q.written = true;
+          }
+        }
+      }, 100);
```
Comment (jordanaustin) [inline src/Device.js]: As discussed we can go back to 10ms on this interval

**Comment by jordanaustin** [comment]
Looks good!
